# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "testsmith"
client_id = "e7a0a5d1ea0b1befa3a702c43f2de52a"
application_url = "https://irs-zambia-pop-appliances.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_script_tags,write_script_tags,read_themes,write_themes,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://irs-zambia-pop-appliances.trycloudflare.com/auth/callback",
  "https://irs-zambia-pop-appliances.trycloudflare.com/auth/shopify/callback",
  "https://irs-zambia-pop-appliances.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "om-test12.myshopify.com"
